### ISSUE TITLE
README: try SIMDe online

### ISSUE THREAD

**Issue by FaresSalem** [nemequ/simde#116]
It seems that (try SIMDe online) needs an update or fixing, it directs me to this link https://github.com/nemequ/simde/blob/master/simde.netlify.com/godbolt/demo

**Comment by nemequ** [comment]
Oops, that should be https://simde.netlify.com/godbolt/demo (or https://simde.netlify.com/godbolt/simple if you just want a single compiler).  I'll fix it ASAP, thanks for reporting!

**Comment by FaresSalem** [comment]
No worries, just merge it to master :D

**Comment by nemequ** [comment]
Yep, done. It just takes a while to get through CI, and the master branch is protected to make sure changes *always* go through CI… for patches like this it's silly, but in general I think it's a good thing :)

**Comment by junaruga** [comment]
In case of this kind of commit, you can skip the Travis CI check by including `[<KEYWORD> skip]` or `[skip <KEYWORD>]` in the commit message. See https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build for detail.

**Comment by FaresSalem** [comment]
Thanks for mentioning @junaruga, will we can add that to CONTRIBUTING.md as a notice I think

**Comment by nemequ** [comment]
> In case of this kind of commit, you can skip the Travis CI check by including `[<KEYWORD> skip]` or `[skip <KEYWORD>]` in the commit message. See https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build for detail.

Good point.  It's not just Travis; I know this works on at least Circle CI and AppVeyor, probably others as well.  I don't think it will work for SIMDe, though.

IIRC on some of them [ci skip] needs to appear in the commit title (the first line), which is a great way to make commit logs uglier :(

The real problem, however, is that the master branch is [protected](https://help.github.com/en/github/administering-a-repository/about-protected-branches) so it's not possible to push a commit to it unless it has passed CI.  I could disable this feature, but I'd rather have it than than `[ci skip]`; it has prevented me from pushing bad code to master on several occasions (though I'd probably be more careful if I didn't know master was protected…).

**Comment by FaresSalem** [comment]
@nemequ Actually it works, I’ve tried testing it on my own fork, see the commits just above your comment, the point is that, Yup uglier logs :/

**Comment by nemequ** [comment]
It works to skip the CI builds, but you can't push the commits to the master branch of this repository.  You'll end up with something like:

```
# git push ci master
Enumerating objects: 146, done.
Counting objects: 100% (146/146), done.
Delta compression using up to 4 threads
Compressing objects: 100% (80/80), done.
Writing objects: 100% (128/128), 48.05 KiB | 3.00 MiB/s, done.
Total 128 (delta 100), reused 58 (delta 46)
remote: Resolving deltas: 100% (100/100), completed with 14 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "continuous-integration/travis-ci" is expected.
To github.com:nemequ/simde.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:nemequ/simde.git'
```

**Comment by junaruga** [comment]
Does using a pull-request with `[ci skip]` have a problem for this repository? I do not understand the context well.

Perhaps, Github Actions needs following setting to use `[ci skip]`. I found a good example by change today. :)

https://github.com/puma/puma/blob/master/.github/workflows/ruby.yml#L14-L16

```
    if: |
      !(contains(github.event.pull_request.title, '[ci skip]')
        || contains(github.event.head_commit.message, '[ci skip]'))
```

**Comment by nemequ** [comment]
I guess it depends on what you mean by "problem".

With a protected branch, GitHub will refuse any requests to push to the protected branch unless CI has completed successfully on that exact commit ID already.

If someone creates a PR with `[ci skip]`, the CI service will not report back that the build was successful (since it wasn't), so GitHub will refuse requests to push that commit ID to the protected branch.

GitHub can be configured to allow *forced* pushes to protected branches even if CI doesn't succeed, but it's generally best to avoid forced pushes to public branches like master.  It should be safe if the push would have worked if it weren't for the branch protection, but I don't like to do it since it's too easy to make a mistake which will annoy anyone using the repo.

So, if you open a PR with `[ci skip]` in the commit message, I basically won't be able to push it to master without getting rid of the `[ci skip]` and pushing it to a branch first.  The other option is to add another commit on top of the skipped commit.  GitHub only looks at the tip of the branch; CI needn't have successfully built *every* commit, just the tip.  This is actually quite likely to happen anyways; I tend to merge multiple commits since usually when I'm looking at PRs I have a few changes in my local repo, and I tend to merge them all at once.

Also, even if it weren't for protected branches I'd probably edit the commit message to remove `[ci skip]`; I like clean (and linear) commit logs.

So, `[ci skip]` probably doesn't really matter for PRs to SIMDe one way or another.  It may or may not create a few seconds of extra work for me, and it may or may not save a build on CI.

**Comment by nemequ** [comment]
I guess I should close this issue since it has been resolved, but I don't mean to cut off the discussion; if anyone still has questions about this feel free to post.

**Comment by junaruga** [comment]
> If someone creates a PR with [ci skip], the CI service will not report back that the build was successful (since it wasn't), so GitHub will refuse requests to push that commit ID to the protected branch.

Now I understand it correctly maybe. Thank you for the explanation.
I did not know the fact "GitHub will refuse requests to push that commit ID to the protected branch".
`[ci skip]` is often used in [Ruby's github repository](https://github.com/ruby/ruby/commits/master). I do not know how they manage it.

**Comment by nemequ** [comment]
They probably don't enable branch protection.  I don't think it's a particularly common setting.
