### ISSUE TITLE
MMX.h define fixes, SSE.h typo fix, compiler warning fix

### ISSUE THREAD

**Issue by jsbache** [nemequ/simde#122]
I have a number of fixes to the headers, but I don't have the rights to open a PR,.
Is it possible to be added to this depot as a contributor?
[mmx.txt](https://github.com/nemequ/simde/files/4396269/mmx.txt)
[sse.txt](https://github.com/nemequ/simde/files/4396270/sse.txt)
[ssse3.txt](https://github.com/nemequ/simde/files/4396271/ssse3.txt)

**Comment by nemequ** [comment]
Hi @jsbache.  Thanks for your interest in contributing!

Actually, anyone on GitHub has the necessary rights to open a pull request.  You just need to [fork SIMDe](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) first, then make your changes in the fork.  After that, you should be able to [create a pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) from your fork to SIMDe.

I'm a bit nervous about adding someone I don't know as a contributor, especially since you don't seem to be very familiar with git (or possibly GitHub), although the fact that all the changes in the files you attached seem solid is encouraging.  Based on your use of the word "depot", I'm guessing your experience is mostly with Perforce?

Since you've already attached the changes, if you just want to get them upstreamed and be done with this I'd be happy to merge them for you (using your name and e-mail address as the author, of course).

On the other hand, if you'd like to familiarize yourself with the normal development process I'd be happy to help you through it.  If you have any questions feel free to ask here, via e-mail, or if you prefer we can arrange a chat session.

**Comment by jsbache** [comment]
If the changes look good to you then go ahead and integrate.
(while I do have a background using perforce, for the last year I have used git, but mainly inside my company repo which simply operates with branches. Hence my mistaken assumption about the workflow).
If I find further issues, I will create a fork and a PR.
Thank you for a prompt response.

**Comment by nemequ** [comment]
Ah, that explains it.

I've committed most of the changes, but this one seems wrong:

```diff
diff --git a/simde/x86/ssse3.h b/simde/x86/ssse3.h
index 9929c72..c5a2582 100644
--- a/simde/x86/ssse3.h
+++ b/simde/x86/ssse3.h
@@ -279,7 +279,7 @@ simde_mm_alignr_epi8 (simde__m128i a, simde__m128i b, int count) {
   if (HEDLEY_UNLIKELY(count > 31))
     return simde_mm_setzero_si128();
 
-  for (size_t i = 0 ; i < (sizeof(r_.i8) / sizeof(r_.i8[0])) ; i++) {
+  for (int i = 0 ; i < (sizeof(r_.i8) / sizeof(r_.i8[0])) ; i++) {
     const int srcpos = count + i;
     if (srcpos > 31) {
       r_.i8[i] = 0;
@@ -314,7 +314,7 @@ simde_mm_alignr_pi8 (simde__m64 a, simde__m64 b, const int count) {
   if (HEDLEY_UNLIKELY(count > 15))
     return simde_mm_setzero_si64();
 
-  for (size_t i = 0 ; i < (sizeof(r_.i8) / sizeof(r_.i8[0])) ; i++) {
+  for (int i = 0 ; i < (sizeof(r_.i8) / sizeof(r_.i8[0])) ; i++) {
     const int srcpos = count + i;
     if (srcpos > 15) {
       r_.i8[i] = 0;
```

Depending on the compiler and flags, it may generate a warning about comparing signed (`int`) and unsigned (`size_t`, from the `sizeof` operators) types.  Do you remember what you were trying to fix here?  Maybe `const int srcpos = count + ((int) i);` would be better?

**Comment by jsbache** [comment]
"count" is int and "i" is size_t. On LP64 (macOs/iOS) we have: sizeof(int) == 4 and sizeof(size_t) == 8 hence you will get a warning.
the for statement seemed to need to iterate fewer than 2^31 elements and as such using int for both "count" and "i" seemed like the right solution (int is "supposed" to be the most efficient datatype on the target architecture)

**Comment by nemequ** [comment]
That makes sense, thanks for the explanation.

I think I'm going to go with what I posted.  If I use `int` in the loop -Wsign-compare will emit a diagnostic (which is why I use `size_t` in all the loops).  If it weren't for that I think `int` would make more sense.

This prompted me to go through and clean up a bunch of warnings from clang (`-Weverything -Wno-padded -Wno-extra-semi -Wno-double-promotion -Wno-used-but-marked-unused -Wno-vla -Wno-zero-as-null-pointer-constant`), so hopefully there will be fewer problems like this, but please let me know if you find more.
