### ISSUE TITLE
The build for the tests fails on clang-10, 9, ppc64le

### ISSUE THREAD

**Issue by junaruga** [nemequ/simde#127]
On the master branch commit: `434b6272e1db863e743cc994f760274d2ecd1e8d` applying [this patch](https://github.com/nemequ/simde/issues/124#issuecomment-605676540), the unit test's `make` after `cmake ..` fails on Fedora ppc64le, both clang-10 (10.0.0) and clang-9 (9.0.1).
This error happens on ppc64le, but does not happen on x86_64, and aarch64 clang-10 and clang-9.

All the log is [here](https://gist.github.com/junaruga/80884905b503bd5f2c90675965eefedd).
Do you have any idea to fix it? Thank you.

```
$ clang --version
clang version 10.0.0 (Fedora 10.0.0-0.11.rc6.fc33)
Target: powerpc64le-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ clang++ --version
clang version 10.0.0 (Fedora 10.0.0-0.11.rc6.fc33)
Target: powerpc64le-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

```
$ mkdir test/build-clang
$ cd test/build-clang
$ CC=clang CXX=clang++ cmake ..
$ make -O -j4 V=1 VERBOSE=1
...
...
/usr/lib64/clang/10.0.0/include/altivec.h:55:19: error: unknown type name 'vector'
static __inline__ vector bool char __ATTRS_o_ai
                  ^
...
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

**Comment by nemequ** [comment]
It looks like the problem happens when you include stdbool.h (which defines `bool` to `_Bool`) before including altivec.h.  I can reproduce it with

```c
#include <stdbool.h>
#include <altivec.h>
```

I filed [bug #45365](https://bugs.llvm.org/show_bug.cgi?id=45365) against clang for this, but I wouldn't be surprised if it doesn't get fixed.  Either way, I think I need to try to get rid of <stdbool.h>… I can tweak µnit a bit to get rid of it, I'm just worried something else will pull it in, too.
