### ISSUE TITLE
RFC: Probably stupid suggestion: just divide and conquer

### ISSUE THREAD

**Issue by rosbif** [nemequ/simde#136]
RFC: Why not simply adopt a divide and conquer solution?

I have noticed that for all the (many) intrinsics that I use:-
All 512-bit intrinsics can be almost trivially and efficiently rewritten as two 256-bit intrinsics, rarely more.
All 256-bit intrinsics can be almost trivially and efficiently rewritten as two 128-bit intrinsics, rarely more.

I think that we can consider SSE4.2 (or perhaps even SSE2) as a minimum baseline but we could continue further.

For instance (very simplified):-

In 512-bit header

simde_mm512_my_operation() {
#if CPU_HAS_512
  _mm512_my_operation();
#else
  simde_mm256_my_operation();
  simde_mm256_my_operation();
#endif
}

In 256-bit header

simde_mm256_my_operation() {
#if CPU_HAS_256
  _mm256_my_operation();
#else
  simde_mm128_my_operation();
  simde_mm128_my_operation();
#endif
}

In 128-bit header

simde_mm128_my_operation() {
#if CPU_HAS_128
  _mm128_my_operation();
#else
  simde_straight_C_coded_my_operation();
#endif
}

Can anyone see any intrinsics which don't easily fall into this type of decomposition?

Even if there are, I am sure that the vast majority of intrinsics can be easily handled by divide and conquer.

Another beauty of this approach is that there would be an enormous number of highly stereotyped functions which could be generated automatically from the "inner function name" by a macro processor, possibly even the C preprocessor.

For instance there are lots of intrinsics like:
                    r = some_full_sized_function(a, b)
which can be decomposed into:
      top_half_r = some_half_sized_function(     top_half_a,        top_half_b)
bottom_half_r = some_half_sized_function(bottom_half_a, bottom_half_b)

Moreover generating these by macros would avoid copy/paste errors like those I corrected recently.

Supporting remarks:-
Some AMD processors supporting AVX2 do this with no 256-bit execution unit, only 128-bit ones.
Even on Intel AVX2 has virtually zero cross-lane operations.
Operations which should logically be cross-lane are not: for instance 256-bit byte shifts are in fact two 128-bit byte shifts.
To perform a 256-bit byte shift the programmer has to save and restore the byte(s) which would be shifted out.
Been there; done that ;-)

**Comment by nemequ** [comment]
Not a stupid suggestion at all.  It's quite reasonable.

The vast majority of intrinsics work like you describe, but there are are decent number that don't; most of the shuffle ones come to mind, and some bit shifting code like `_mm_slli_si128`.  As a percentage it's pretty low, but it's still a decent number of functions.

The basic approach is what we're trying to do for larger vectors, though as you've seen there are quite a few functions where we haven't done it yet.  While the basic idea is sound, there would have to be a *lot* of special cases.  A few problems that come to mind:

 * It would leave a lot of optimization opportunities on the table.  Sometimes you can do stuff a *lot* faster than just calling the shorter version twice.  This is the main reason SIMDe is structured the way it is.
 * It would make the code much more difficult to understand and reason about.  We already have more macro magic than I'd like.
 * There are often no comparable functions.  AVX-512 is a major offender here.
 * Often the "shorter" way is in the same ISA extension (or sometimes even a later one).  For example, `_mm_blendv_epi8`.
 * Sometimes the compiler is able to generate better code for the "portable" fallback of a larger version.  This was just happening to me a couple days ago on clang (although GCC did much better with 2 × the smaller operation).
 * If we have support for larger vectors but not the operation in question, it can be faster to use alternate methods with larger vectors.  For example, `_mm256_and_si256` (AVX2) should probably use `_mm256_and_ps` (AVX) if available instead of 2 × `_mm_and_si128`.
 * Non-x86 intrinsics.  Most CPUs these days only support 128-bit vectors, but ARM has SVE, and RISC-V is planning something similar.
 * The names may not be the same (yes, really.  I can't think of examples right now, but I do remember seeing it happen in Intel's APIs).
 * Sometimes we have to do some extra work to convert to 2 × smaller operations.
 * Compiler bugs or missing functions mean we sometimes need special cases.  I actually run into this pretty frequently with SIMDe… PGI has been particularly troublesome, but I've had to work around issues in MSVC, GCC, clang, and ICC.
 * All the special cases would be a problem for consistency.

That is my no means a complete list.  Unfortunately I could go on.

Some of these don't really show up much in the codebase currently because up until recently I've been pretty focused on getting the portable implementations done, not optimizing (i.e., adding non-x86 implementations).

As for the C&P errors you've been finding, obviously they're a bit embarassing, but I'm actually not too troubled.  They can almost always be fixed with a simple search & replace, and they'll disappear pretty quickly as we spend more time working on the code adding optimized versions, and as people actually use SIMDe.  AVX and later just haven't received much attention yet; AVX2 still doesn't have all the portable implementations done, and we've barely started working on AVX-512.

I'm going to close this since I don't think it's really an open issue, but I'm happy to discuss it further if you have any questions.
