### ISSUE TITLE
Problem in simde_mm512_xor_si512 in avx512f.h

### ISSUE THREAD

**Issue by rosbif** [nemequ/simde#164]
See the two lines lines following SIMDE__VECTORIZE.

```
SIMDE__FUNCTION_ATTRIBUTES
simde__m512i
simde_mm512_xor_si512 (simde__m512i a, simde__m512i b) {
  #if defined(SIMDE_AVX512F_NATIVE)
    return _mm512_xor_si512(a, b);
  #else
    simde__m512i_private
      r_,
      a_ = simde__m512i_to_private(a),
      b_ = simde__m512i_to_private(b);

  #if defined(SIMDE_ARCH_X86_AVX2)
    r_.m256i[0] = simde_mm256_xor_si256(a_.m256i[0], b_.m256i[0]);
    r_.m256i[1] = simde_mm256_xor_si256(a_.m256i[1], b_.m256i[1]);
  #elif defined(SIMDE_ARCH_X86_SSE2)
    r_.m128i[0] = simde_mm_xor_si128(a_.m128i[0], b_.m128i[0]);
    r_.m128i[1] = simde_mm_xor_si128(a_.m128i[1], b_.m128i[1]);
    r_.m128i[2] = simde_mm_xor_si128(a_.m128i[2], b_.m128i[2]);
    r_.m128i[3] = simde_mm_xor_si128(a_.m128i[3], b_.m128i[3]);
  #elif defined(SIMDE_VECTOR_SUBSCRIPT_OPS)
    r_.i32f = a_.i32f ^ b_.i32f;
  #else
    SIMDE__VECTORIZE
    for (size_t i = 0 ; i < (sizeof(r_.i64) / sizeof(r_.i64[0])) ; i++) {
      r_.i32f[i] = a_.i32f[i] ^ b_.i32f[i];
    }
  #endif

  return simde__m512i_from_private(r_);
#endif
}
#if defined(SIMDE_AVX512F_ENABLE_NATIVE_ALIASES)
#  define _mm512_xor_si512(a, b) simde_mm512_xor_si512(a, b)
#endif

```
Git blames me for this but I am sure I used i64 in both lines.
Maybe you changed the second line to i32f.

Should I avoid i64?
Is i32f faster?
(Or perhaps some of your machines don't support 64-bit operations.)

So would you prefer that I correct the loop count to i32f or the operation to i64?

**Comment by nemequ** [comment]
> Maybe you changed the second line to i32f.
>
> Should I avoid i64?
> Is i32f faster?

Sorry, yes, I probably did.  IIRC I was merging several patches there, I thought that was part of a different one.

You shouldn't avoid i64 if that's the type you actually need to operate on, but when we don't care about the element size yes, i32f is better since it may be faster on some architectures.  For x86_64 it should be the same since IIRC `int_fast32_t`  in 64 bits, but on x86 it's 32 bits.  Basically, for most `*_si*` functions `i32f` is the correct choice.

I pushed a commit to staging to fix this, I'll merge it into master as soon as CI finishes.
