### ISSUE TITLE
Big-endian tests

### ISSUE THREAD

**Issue by rosbif** [nemequ/simde#261]
This is not really an issue but maybe someone can help.
I am developing some code which I suspect may have endian problems.
I want to test this code locally on a big-endian platform without creating a PR and generating the noise associated with likely s390x failures.
I am running Ubuntu 20.04 and  I have tried its qemu 4.2.0 on four platforms.
Unfortunately it dumps core on both the big-endian platforms I tried, even on a classic hello.c :-(
```
On s390x qemu dumps core
+ s390x-linux-gnu-gcc hello.c
+ qemu-s390x -L /usr/s390x-linux-gnu a.out
./testHello: line 6:  3304 Segmentation fault      (core dumped) qemu-s390x -L /usr/s390x-linux-gnu a.out
+ set +x

On aarch64 OK
+ aarch64-linux-gnu-gcc hello.c
+ qemu-aarch64 -L /usr/aarch64-linux-gnu a.out
Hello world!
+ set +x

On mips64 qemu dumps core
+ mips64-linux-gnuabi64-gcc hello.c
+ qemu-mips64 -L /usr/mips64-linux-gnuabi64 a.out
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
./testHello: line 18:  3322 Segmentation fault      (core dumped) qemu-mips64 -L /usr/mips64-linux-gnuabi64 a.out
+ set +x

On mips64el OK
+ mips64el-linux-gnuabi64-gcc hello.c
+ qemu-mips64el -L /usr/mips64el-linux-gnuabi64 a.out
Hello world!
+ set +x

```
Has anyone managed to get this to work?
(Remark: I also tried docker but ran into a newbie problem and didn't insist.)

**Comment by nemequ** [comment]
I had a similar problem with s390x on Debian for a while, but it works now.  Maybe the fixes have yet to percolate out to Ubuntu?

For what it's worth, I run Fedora but I have a Debian Unstable VM with all the cross compilers installed (Debian's support for cross-compilation is much better); if you have spare RAM it's a decent way to go.  I just mount the home directory using sshfs and ssh in, so it feels very native.

Another option is that you could sign up for Travis (it's free) for your fork.  I actually have [https://github.com/nemequ/ci-noise](a repo) which I use when I want to run stuff through CI without generating a ton of noise in SIMDe (or whatever I'm working on).  You can even temporarily comment out builds other than the one you're interested in (e.g., s390x) in .travis.yml so it doesn't take forever.

If you want to get Ubuntu working though (which seems pretty reasonable to me), I think [Ask Ubuntu](https://askubuntu.com/) or maybe [Ubuntu Forums](https://ubuntuforums.org/) would probably be the place to go.  Back when I was using Ubuntu (IIRC I switched to Debian before 5.10 was released) Ubuntu Forums was the place to go, but I get the impression Ask Ubuntu is more active these days.

I'm going to close this since it's not really an issue, but we can obviously keep talking here.
