### ISSUE TITLE
[x86-64 clang 10] simde/x86/avx.h:2066:52: error: no member named 'isnan' in namespace 'std'; did you mean simply 'isnan'?

### ISSUE THREAD

**Issue by mr-c** [nemequ/simde#282]
https://travis-ci.org/github/soedinglab/MMseqs2/jobs/685107675#L344

**Comment by nemequ** [comment]
Looks like C++98 doesn't support `isnan`.  I'll try to find a C++98-compliant solution.

**Comment by nemequ** [comment]
I'm having trouble reproducing this, even with the same version of g++.  Can you change the `make` to `make VERBOSE=1` us I know what flags are being passed to the compiler?

**Comment by mr-c** [comment]
@nemequ https://travis-ci.org/github/soedinglab/MMseqs2/jobs/686080797#L678

**Comment by nemequ** [comment]
Thanks, I can reproduce it now (-std=c++0x was the key).

Now I just need to figure out how to git it working while also not breaking everything else :).  I should have something soon.

**Comment by mr-c** [comment]
This is also an issue for clang 10.0.1 on x86-64: https://travis-ci.org/github/soedinglab/MMseqs2/jobs/686492657#L980

**Comment by nemequ** [comment]
I can't reproduce this; I've tried installing clang-10 on Ubuntu 16.04 and copying the flags.  No luck.

I can't see how this could be anything other than a buggy standard library unless they're doing something crazy like `#define HUGE_VAL ...` instead of including math.h or cmath… `std::isnan` is only emitted if `HUGE_VAL` is defined but `isnan` isn't and we're in C++ mode.

I added 9d29f2b56ff3a93e4f13ab2075fe043ca10b7e7e to hopefully address this, but without being able to reproduce it I can't be sure.  If it's still present please reopen (again).

**Comment by mr-c** [comment]
Sorry, the bug remains: https://travis-ci.org/github/soedinglab/MMseqs2/jobs/688251145#L992

Here's a reproducer:

``` Dockerfile
FROM ubuntu:focal-20200423
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        clang \
        cmake \
        git \
        libbz2-dev \
        libc++-10-dev \
        libomp-dev \
        xxd \
        zlib1g-dev \
        && rm -rf /var/lib/apt/lists/*
WORKDIR /src
RUN git clone --branch simde --depth=50 --recurse-submodules https://github.com/mr-c/MMseqs2
WORKDIR /build
RUN CC=clang-10 CXX=clang++-10 cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DHAVE_MPI=0 -DHAVE_TESTS=1 /src/MMseqs2 ; make -j$(nproc)
```

**Comment by nemequ** [comment]
That Dockerfile works for me.  https://paste.centos.org/view/e643c8e8

**Comment by mr-c** [comment]
@nemequ Ah, sorry, I should have put that commit there, or made a different branch

**Comment by nemequ** [comment]
Okay, it looks like the problem is -stdlib=libc++, which has [its own math.h](https://github.com/llvm/llvm-project/blob/master/libcxx/include/math.h) where they define [an `isnan` *function*](https://github.com/llvm/llvm-project/blob/364c595403c00431374dbcc965b6117e33a7f140/libcxx/include/math.h#L502) but no `isnan` *macro*.  AFAIK the `isnan` function isn't defined in any standard, and the C standard specifically requires that `isnan` be a macro.  Since we don't see an `isnan` function (but we know a math.h/cmath header has been included since `HUGE_VAL` is defined), we assume we should be using the standard `std::isnan` function, but libc++ doesn't define it.

Technically this doesn't violate the C++ standard since math.h is a C include and, AFAIK, the C++ standard has nothing to say about it.  One would think that would mean libc++ would actually adhere to the C standard for this, but no, apparently not.  It does violate the C standard, but I don't think they care.

I've added some tests to check for the include guards libc++ uses for math.h and cmath.  That fixes the issue for me, though of course it's a somewhat fragile solution.  The commit is in CI right now, should be hitting master soon.
