### ISSUE TITLE
ppc4el plink2 build issues

### ISSUE THREAD

**Issue by mr-c** [nemequ/simde#396]
```
cc -O2 -std=gnu99 -DZSTD_MULTITHREAD -Wall -Wextra -Wshadow -Wformat-security -I../zstd/lib -I../zstd/lib/common -c
g++ -Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -DSIMDE_ENABLE_OPENMP -fopenmp-simd -O3 -std=c++11 -O2 -DZSTD_MULTITHREAD   -Wall -Wextra -Wshadow -Wformat-security -Wold-style-cast ../include/plink2_base.cc ../include/plink2_bits.cc ../include/pgenlib_misc.cc ../include/pgenlib_read.cc ../include/pgenlib_write.cc ../include/plink2_bgzf.cc ../include/plink2_stats.cc ../include/plink2_string.cc ../include/plink2_text.cc ../include/plink2_thread.cc ../include/plink2_zstfile.cc ../plink2.cc ../plink2_adjust.cc ../plink2_cmdline.cc ../plink2_common.cc ../plink2_compress_stream.cc ../plink2_data.cc ../plink2_decompress.cc ../plink2_export.cc ../plink2_fasta.cc ../plink2_filter.cc ../plink2_glm.cc ../plink2_help.cc ../plink2_import.cc ../plink2_ld.cc ../plink2_matrix.cc ../plink2_matrix_calc.cc ../plink2_misc.cc ../plink2_psam.cc ../plink2_pvar.cc ../plink2_random.cc ../plink2_set.cc -c
In file included from ../include/plink2_bits.h:23,
                 from ../include/pgenlib_misc.h:77,
                 from ../include/pgenlib_read.h:23,
                 from ../include/pgenlib_read.cc:18:
../include/plink2_base.h: In function ‘uintptr_t plink2::UniVecHsum32(plink2::UniVec)’:
../include/plink2_base.h:1706:25: note: the ABI of passing aggregates with 16-byte alignment has changed in GCC 5
 1706 | HEADER_INLINE uintptr_t UniVecHsum32(UniVec uv) {
      |                         ^~~~~~~~~~~~
In file included from ../include/plink2_bits.h:23,
                 from ../include/pgenlib_misc.h:77,
                 from ../include/pgenlib_read.h:23,
                 from ../include/pgenlib_read.cc:18:
../include/plink2_base.h: In function ‘uintptr_t plink2::UniVecHsum32(plink2::UniVec)’:
../include/plink2_base.h:1706:25: note: the ABI of passing aggregates with 16-byte alignment has changed in GCC 5
 1706 | HEADER_INLINE uintptr_t UniVecHsum32(UniVec uv) {
      |                         ^~~~~~~~~~~~
../plink2_glm.cc: In function ‘plink2::VecF plink2::fmath_exp_ps(plink2::VecF)’:
../plink2_glm.cc:2375:72: error: narrowing conversion of ‘9223372034707292159’ from ‘long long unsigned int’ to ‘float’ [-Wnarrowing]
 2375 |   const __m128i mask7ff = {0x7fffffff7fffffffLLU, 0x7fffffff7fffffffLLU};
      |                                                                        ^
../plink2_glm.cc:2375:72: error: narrowing conversion of ‘9223372034707292159’ from ‘long long unsigned int’ to ‘float’ [-Wnarrowing]
../plink2_glm.cc:2378:70: error: narrowing conversion of ‘4805340803523149824’ from ‘long long unsigned int’ to ‘float’ [-Wnarrowing]
 2378 |   const __m128i max_x = {0x42b0000042b00000LLU, 0x42b0000042b00000LLU};
      |                                                                      ^
../plink2_glm.cc:2378:70: error: narrowing conversion of ‘4805340803523149824’ from ‘long long unsigned int’ to ‘float’ [-Wnarrowing]
```

From https://buildd.debian.org/status/fetch.php?pkg=plink2&arch=ppc64el&ver=2.00%7Ea3-200511%2Bdfsg-1&stamp=1592569335&raw=0

**Comment by nemequ** [comment]
The problem here is that assigning a `__m128i` like relies on `__m128i` being implemented as a GCC-style vector extension of two 64-bit values.  It's not at all standard.  The "correct" way to do this is to use `_mm_set_epi64x`.  For example, instead of

```c
const __m128i mask7ff = {0x7fffffff7fffffffLLU, 0x7fffffff7fffffffLLU};
```

```c
__m128i mask7ff = _mm_set_epi64x(0x7fffffff7fffffffLLU, 0x7fffffff7fffffffLLU);
```

Of course, in this case both values are the same, so you should really use `_mm_set1_epi64x`, though that was missing in Visual Studio until 2015:

```c
__m128i mask7ff = _mm_set1_epi64x(0x7fffffff7fffffffLLU);
```

They are passing an unsigned value (notice the `U` at the end), but it should really be signed.  Depending on the warning flags that will actually generate a diagnostic, but obviously they haven't had that warning enabled.  Really, the right way to write that if you care about portability is to use `INT64_C(0x7fffffff7fffffff)`.

But I sincerely doubt that's what they're really trying to do.  Based on the pattern they probably want four 32-bit integers:

```c
__m128i mask7ff = _mm_set1_epi32(INT32_C(0x7fffffff));
```

I'm guessing the reason they were using what they did is they wanted to make the variable const, and the only way to do that is to use the non-portable assignment syntax, which meant they also had to use 64-bit integers (since on GCC __m128i is a vector of 2 `long long`s).  The U was probably just a mistake.

However, the compiler will actually generate exactly the same code for the `_mm_set1_epi32` version I posted above, and it will work correctly on all compilers (even MSVC), doesn't have any issues with endianness, and is a bit easier for compilers to optimize on other other platforms.

With all that said, I don't know why `__m128i` is a vector of *floats* on AltiVec instead of an integer type.  I'll change that.

**Comment by mr-c** [comment]
It gets better :-) https://sources.debian.org/src/plink2/2.00%7Ea3-200511+dfsg-1/plink2_glm.cc/#L2391

**Comment by nemequ** [comment]
Eek.  Well, it should work now, at least on little-endian + IEEE 754.

Hopefully in the future they can use SVML there; SVML has an `_mm_exp_ps` function.  We haven't really done any optimization yet, though, so right now it basically just calls `__builtin_exp` in a loop… which *may* actually be faster than what they have, depending on how good the compiler does at auto-vectorizing it.

**Comment by mr-c** [comment]
Another issue from the same source:

```
powerpc64le-linux-gnu-gcc  -O2 -std=gnu99 -DZSTD_MULTITHREAD   -Wall -Wextra -Wshadow -Wformat-security  ../include/SFMT.c -c
In file included from ../include/SFMT.h:133,
                 from ../include/SFMT.c:49:
../include/SFMT.c: In function 'sfmt_gen_rand_all':
../include/SFMT.c:170:9: error: argument 1 must be a 5-bit signed literal
  170 |     v = _mm_slli_epi32(d, 18);
      |         ^~~~~~~~~~~~~~
```

I'm guessing this is due to https://github.com/nemequ/simde/blob/5fb12ac75ed89611321321700a088909968ee022/simde/x86/sse2.h#L5141 ?

**Comment by mr-c** [comment]
> Syntax
> d=vec_splat_u32(a)
> a must be a signed literal with a value in the range -16 to 15 inclusive.

https://www.ibm.com/support/knowledgecenter/SSGH2K_13.1.3/com.ibm.xlc1313.aix.doc/compiler_ref/vec_splat_u32.html

**Comment by mr-c** [comment]
Maybe a `SIMDE_CONSTIFY_S32_` macro is needed..

**Comment by nemequ** [comment]
`vec_splat_u32` should be `vec_splats`.

**Comment by mr-c** [comment]
@nemequ Thanks! I'm making a fix and test case for imm8 > 15
