### ISSUE TITLE
How about for ARMv8?

### ISSUE THREAD

**Issue by crazy-william** [nemequ/simde#43]
I'm testing ARMv8, and set -march="armv8-a+crc", but the testing "CFLAG__mfpu_neon" is failed.
How can I use neon in correct way?

**Comment by jeffdaily** [comment]
The only arm system I have is a raspberry.  Otherwise, I test the arm builds using a gcc cross-compiler via ubuntu.  For example (in my .travis.yml file), gcc-arm-linux-gnueabihf, gcc-aarch64-linux-gnu, gcc-powerpc-linux-gnu, gcc-arm-linux-gnueabi.

Do you know which cross compiler might correspond to your build flag?

**Comment by nemequ** [comment]
Maybe armv8-a+crc includes NEON already?  Can you look to see if `__ARM_NEON` is defined (`cc -march=armv8-a+crc -dM -E - </dev/null | grep __ARM_NEON` should be sufficient)?

I'm going to close this since determining the right compiler flags is currently outside the scope of the project, but I don't have any problem discussing the issue here.
